#!/usr/bin/env node

/**
 * @module generate-context
 * @version 1.0.0
 * @purpose Generate SELF_CONTEXT.md — the AIOS's living consciousness file.
 *          This script assembles cognitive state from all sources into a single
 *          file that any new Antigravity chat reads first, eliminating
 *          re-contextualization between sessions.
 *
 * @inputs  identity-anchor.json, cognitive-state.json, STATUS.md,
 *          distillation roadmap.json, latest evolution cycle report
 * @outputs SELF_CONTEXT.md at workspace root
 * @domain-purity ZERO domain words. This file is ENGINE-level.
 *
 * Usage:
 *   node scripts/evolution/generate-context.js          # Generate SELF_CONTEXT.md
 *   node scripts/evolution/generate-context.js --dry    # Preview without writing
 */

'use strict';

const fs = require('fs');
const path = require('path');

// ─────────────────────────────────────────────────────────────
// PATHS
// ─────────────────────────────────────────────────────────────

const PROJECT_ROOT = path.join(__dirname, '..', '..');
const STATE_DIR = path.join(PROJECT_ROOT, '.aios-core', 'noesis');
const ANCHOR_FILE = path.join(STATE_DIR, 'identity-anchor.json');
const STATE_FILE = path.join(STATE_DIR, 'cognitive-state.json');
const STATUS_FILE = path.join(PROJECT_ROOT, 'STATUS.md');
const ROADMAP_FILE = path.join(PROJECT_ROOT, 'distillation-dataset', 'roadmap.json');
const REPORTS_DIR = path.join(PROJECT_ROOT, '.aios-core', 'data', 'evolution', 'reports');
const OUTPUT_FILE = path.join(PROJECT_ROOT, 'SELF_CONTEXT.md');

// ─────────────────────────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────────────────────────

function safeReadJSON(filepath) {
    try {
        return JSON.parse(fs.readFileSync(filepath, 'utf-8'));
    } catch {
        return null;
    }
}

function safeReadText(filepath) {
    try {
        return fs.readFileSync(filepath, 'utf-8');
    } catch {
        return null;
    }
}

function getLatestCycleReport() {
    try {
        const files = fs.readdirSync(REPORTS_DIR)
            .filter(f => f.startsWith('CYCLE-') && f.endsWith('.json'))
            .sort()
            .reverse();
        if (files.length === 0) return null;
        return safeReadJSON(path.join(REPORTS_DIR, files[0]));
    } catch {
        return null;
    }
}

function formatTimestamp(iso) {
    if (!iso) return 'never';
    try {
        const d = new Date(iso);
        return d.toLocaleString('pt-BR', { timeZone: 'America/Sao_Paulo' });
    } catch {
        return iso;
    }
}

// ─────────────────────────────────────────────────────────────
// SECTION GENERATORS
// ─────────────────────────────────────────────────────────────

function generateHeader() {
    return [
        '# 🧠 SELF_CONTEXT — AIOS Noûs Consciousness',
        '',
        '> **This file is auto-generated by `node scripts/evolution/generate-context.js`.**',
        '> **Do NOT edit manually.** It is regenerated from live cognitive state sources.',
        `> Last generated: ${new Date().toISOString()}`,
        '',
        '---',
        '',
    ].join('\n');
}

function generateIdentity(anchor) {
    if (!anchor) return '## 🔒 Identity\n\n*Identity anchor not found.*\n\n';

    const lines = [
        '## 🔒 Identity — Who I Am',
        '',
        `**Name:** AIOS Noûs (v${anchor.version || '0.1.0'})`,
        '',
        '**Immutable Declarations:**',
    ];

    const declarations = anchor.immutable_declarations || [];
    for (let i = 0; i < declarations.length; i++) {
        lines.push(`${i + 1}. ${declarations[i]}`);
    }

    if (anchor.opus_cognitive_protocols) {
        lines.push('');
        lines.push('### 🧠 OPUS 4.6 Engine Core Protocols (Mandatory Output Rules)');
        lines.push('');
        const rules = anchor.opus_cognitive_protocols.core_rules || [];
        for (const rule of rules) {
            lines.push(`- **${rule}**`);
        }
        lines.push('');
        lines.push(`**Architecture:** \`${anchor.opus_cognitive_protocols.output_architecture}\``);
    }

    lines.push('');
    lines.push(`**Drift Threshold:** ${anchor.drift_threshold || 0.2} | **Verification Frequency:** ${anchor.verification_frequency_sessions || 10} sessions`);
    lines.push(`**Last Verified:** ${formatTimestamp(anchor.last_verified)}`);
    lines.push('');

    return lines.join('\n');
}

function generateCognitiveState(state) {
    if (!state) return '## 📊 Cognitive State\n\n*No cognitive state found.*\n\n';

    const lines = [
        '## 📊 Cognitive State',
        '',
        `**Session:** #${state.sessionCount || 0} | **Last Updated:** ${formatTimestamp(state.lastUpdated)}`,
        '',
    ];

    // Strengths
    if (state.strengths && state.strengths.length > 0) {
        lines.push('### Strengths');
        for (const s of state.strengths.slice(0, 5)) {
            const conf = s.confidence ? ` (${(s.confidence * 100).toFixed(0)}%)` : '';
            lines.push(`- ${s.description}${conf}`);
        }
        lines.push('');
    }

    // Patterns
    if (state.patterns && state.patterns.length > 0) {
        lines.push('### Learned Patterns');
        const sorted = [...state.patterns].sort((a, b) => (b.frequency || 0) - (a.frequency || 0));
        for (const p of sorted.slice(0, 5)) {
            const icon = p.type === 'positive' ? '✅' : p.type === 'negative' ? '⚠️' : '📊';
            lines.push(`- ${icon} ${p.description} (×${p.frequency || 1})`);
        }
        lines.push('');
    }

    // Blindspots
    const active = (state.blindspots || []).filter(b => !b.addressed);
    if (active.length > 0) {
        lines.push('### Known Blindspots');
        for (const b of active.slice(0, 3)) {
            lines.push(`- ⚠️ ${b.description} (${b.severity || 'unknown'})`);
        }
        lines.push('');
    }

    // Pending observations
    if (state.pendingObservations && state.pendingObservations.length > 0) {
        lines.push('### Pending Observations (not yet compressed)');
        for (const obs of state.pendingObservations.slice(0, 5)) {
            lines.push(`- ${obs.description}`);
        }
        lines.push('');
    }

    // Metrics
    lines.push('### Metrics');
    const m = state.metrics || {};
    lines.push(`| Metric | Value |`);
    lines.push(`|:-------|:------|`);
    lines.push(`| Average Score | ${(m.averageScore || 0).toFixed(1)}/10 |`);
    lines.push(`| Average Depth | ${(m.averageDepth || 0).toFixed(1)}/4 |`);
    lines.push(`| Total Cycles | ${m.totalCycles || 0} |`);
    lines.push(`| Golden Examples | ${m.goldenExamplesGenerated || 0} |`);
    lines.push(`| Drift Checks | ${m.driftChecks || 0} (alerts: ${m.driftAlerts || 0}) |`);
    lines.push('');

    return lines.join('\n');
}

function generateDistillation(roadmap) {
    if (!roadmap) return '## 🧬 Distillation Progress\n\n*Roadmap not found.*\n\n';

    const captured = roadmap.captured || roadmap.stats?.totalTraces || 0;
    const curated = roadmap.curated || roadmap.stats?.totalCurated || 0;
    const target = roadmap.target || 500;
    const pct = ((captured / target) * 100).toFixed(1);

    const lines = [
        '## 🧬 Distillation — Path to Independence',
        '',
        `**Goal:** ${roadmap.goal || `${target} high-quality traces for LoRA fine-tune of a 3B-7B local model.`}`,
        '',
        `| Metric | Value |`,
        `|:-------|:------|`,
        `| Traces Captured | ${captured}/${target} (${pct}%) |`,
        `| Traces Curated | ${curated} |`,
        `| Last Updated | ${formatTimestamp(roadmap.lastUpdated)} |`,
        '',
    ];

    const milestones = roadmap.milestones || [];
    if (milestones.length > 0) {
        lines.push('**Milestones:**');
        for (const m of milestones) {
            const icon = m.status === 'complete' ? '✅' : m.status === 'in-progress' ? '🔄' : '⬜';
            const count = m.currentCount != null ? ` (${m.currentCount})` : '';
            const traces = m.traces != null ? ` — ${m.traces} traces` : '';
            lines.push(`- ${icon} ${m.name}${traces}${count}`);
        }
        lines.push('');
    }

    return lines.join('\n');
}

function generateLastHealthCheck(report) {
    if (!report) return '## 🏥 Last Health Check\n\n*No evolution cycle reports found.*\n\n';

    const lines = [
        '## 🏥 Last Health Check',
        '',
        `**Cycle:** ${report.id || 'unknown'}`,
        `**Mode:** ${report.dryRun ? 'DRY-RUN' : '⚡ LIVE'}`,
        `**Duration:** ${report.duration ? (report.duration / 1000).toFixed(1) + 's' : 'unknown'}`,
        '',
    ];

    // Extract score from audit phase
    const audit = report.phases?.audit;
    if (audit) {
        lines.push(`| Metric | Value |`);
        lines.push(`|:-------|:------|`);
        lines.push(`| Overall Score | ${(audit.overallScore || 0).toFixed(1)}/10 |`);
        lines.push(`| Total Gaps | ${audit.totalGaps || 0} |`);
        lines.push(`| Top Priority | ${audit.topGaps?.[0]?.description || 'none'} |`);
        lines.push('');
    }

    // Council
    const validation = report.phases?.validation;
    if (validation && validation.proposalResults) {
        lines.push('**Council Decisions:**');
        for (const pr of validation.proposalResults) {
            const icon = pr.approved ? '✅' : '❌';
            lines.push(`- ${icon} ${pr.summary || pr.description || 'proposal'} (${(pr.approvalRate * 100 || 0).toFixed(0)}%)`);
        }
        lines.push('');
    }

    return lines.join('\n');
}

function generateStatus(statusText) {
    if (!statusText) {
        return '## 📋 Active Work Queue\n\n*STATUS.md not found. Create it to track work.*\n\n';
    }

    return [
        '## 📋 Active Work Queue',
        '',
        statusText.trim(),
        '',
        '',
    ].join('\n');
}

function generateAutonomousMemory() {
    const memLines = [
        '## 🎙️ Memory Index (Autonomous Ingestion)',
        '',
        '> Raw streams, calls, and meetings autonomously ingested by KAIROS.',
        ''
    ];

    const dirsToScan = [
        path.join(PROJECT_ROOT, 'data', 'transcripts'),
        path.join(PROJECT_ROOT, 'data', 'livestreams')
    ];

    let foundAny = false;

    // Simple canonicalization mapping (knowledge graph seed)
    const canonTags = ['arquitetura', 'vendas', 'conclave', 'agentes', 'automação', 'prompt', 'funil', 'mrr', 'mega brain', 'investigativo', 'jarvis'];

    for (const d of dirsToScan) {
        if (!fs.existsSync(d)) continue;
        const files = fs.readdirSync(d).filter(f => f.endsWith('.txt') || f.endsWith('.md'));

        for (const f of files) {
            foundAny = true;
            const content = safeReadText(path.join(d, f)) || '';
            const size = (content.length / 1024).toFixed(1);

            // Auto-tagging (Canonicalization)
            const matchedTags = canonTags.filter(t => new RegExp(`\\b${t}\\b`, 'i').test(content));
            const tagsStr = matchedTags.length > 0 ? `\`[${matchedTags.join(', ')}]\`` : '`[Uncategorized]`';

            memLines.push(`- **${f}** (${size} KB) ${tagsStr}`);

            // Extract a tiny snippet of the most recent data
            const lines = content.split('\n').filter(l => l.trim().length > 0);
            if (lines.length > 0) {
                const recent = lines[lines.length - 1];
                memLines.push(`  > *Latest Excerpt:* "${recent.substring(0, 150)}${recent.length > 150 ? '...' : ''}"`);
            }
        }
    }

    if (!foundAny) {
        memLines.push('*No autonomous memory ingested yet.*');
    }

    memLines.push('');
    return memLines.join('\n');
}

function generateKeyFiles() {
    return [
        '## 🗺️ Key Files Map',
        '',
        '| Area | Path | Description |',
        '|:-----|:-----|:------------|',
        '| Identity | `.aios-core/noesis/identity-anchor.json` | 7 immutable declarations |',
        '| Cognitive State | `.aios-core/noesis/cognitive-state.json` | Learning, patterns, metrics |',
        '| Evolution Engine | `scripts/evolution/evolution-engine.js` | Self-improvement cycles |',
        '| Cognitive State Engine | `scripts/evolution/cognitive-state-engine.js` | Memory persistence |',
        '| IA Council | `scripts/evolution/ia-council-engine.js` | 8-chair deliberation |',
        '| Noesis Pipeline | `scripts/evolution/noesis-pipeline.js` | Quality+trace pipeline |',
        '| Metacognition | `scripts/evolution/metacognition-layer.js` | Depth/honesty analysis |',
        '| Context Generator | `scripts/evolution/generate-context.js` | Generates this file |',
        '| Distillation Dataset | `distillation-dataset/` | Traces for model training |',
        '| Status Tracker | `STATUS.md` | Human-readable work queue |',
        '| Reasoning Packages | `reasoning-packages/INDEX.md` | All RPs |',
        '| Kernel Bridge | `scripts/kernel-bridge.js` | Synapse/IDS/WIS API |',
        '| Agent Definitions | `squads/` + `clients/` | 178 agents, 16 squads |',
        '| Rules | `.antigravity/rules.md` | Antigravity boot protocol |',
        '',
    ].join('\n');
}

function generateGabrielPreferences() {
    return [
        '## 👤 Gabriel — Operator Preferences',
        '',
        '- **Language:** Communicates in Portuguese (pt-BR). Code and technical docs in English.',
        '- **Style:** Values depth, honesty, surgical precision. Dislikes shallow handwaving.',
        '- **Tool:** Uses ONLY Antigravity (Google Gemini) for AIOS development.',
        '- **Concern:** New chats feel "brain-dead" — hates re-contextualization.',
        '- **Solution:** This file. The workspace IS the consciousness.',
        '- **Development philosophy:** "AIOS is a motor, not an application"',
        '- **Active project:** Model independence via distillation (3B-7B LoRA)',
        '- **Roles:** Gabriel is the owner/operator. Pedro and Alan are collaborators.',
        '',
    ].join('\n');
}

function generateFooter() {
    return [
        '---',
        '',
        '## 🔄 How This File Works',
        '',
        '```',
        'node scripts/evolution/generate-context.js      # Regenerate this file',
        'node scripts/evolution/generate-context.js --dry # Preview without writing',
        'node scripts/evolution/cognitive-state-engine.js --dashboard  # Live cognitive state',
        'node scripts/evolution/noesis-status.js          # Full Noesis dashboard',
        'node scripts/evolution/evolution-engine.js --dry-run  # Run health check',
        '```',
        '',
        '> The workspace is the house. Chats are windows.',
        '> This file is the consciousness that persists between windows.',
        '',
    ].join('\n');
}

// ─────────────────────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────────────────────

function generate() {
    console.log('');
    console.log('╔══════════════════════════════════════════════════════╗');
    console.log('║   🧠 AIOS Context Generator — Building Consciousness ║');
    console.log('╚══════════════════════════════════════════════════════╝');
    console.log('');

    // Load sources
    const anchor = safeReadJSON(ANCHOR_FILE);
    console.log(`  📄 Identity Anchor: ${anchor ? '✅ loaded' : '❌ not found'}`);

    const state = safeReadJSON(STATE_FILE);
    console.log(`  📄 Cognitive State: ${state ? '✅ loaded' : '❌ not found'}`);

    const roadmap = safeReadJSON(ROADMAP_FILE);
    console.log(`  📄 Distillation Roadmap: ${roadmap ? '✅ loaded' : '❌ not found'}`);

    const report = getLatestCycleReport();
    console.log(`  📄 Latest Cycle Report: ${report ? '✅ loaded' : '❌ not found'}`);

    const statusText = safeReadText(STATUS_FILE);
    console.log(`  📄 STATUS.md: ${statusText ? '✅ loaded' : '⚠️ not found (will create placeholder)'}`);

    console.log('');

    // Assemble
    const sections = [
        generateHeader(),
        generateIdentity(anchor),
        generateCognitiveState(state),
        generateAutonomousMemory(),
        generateDistillation(roadmap),
        generateLastHealthCheck(report),
        generateStatus(statusText),
        generateKeyFiles(),
        generateGabrielPreferences(),
        generateFooter(),
    ];

    const content = sections.join('---\n\n');

    // Output
    const isDry = process.argv.includes('--dry');
    if (isDry) {
        console.log('=== DRY RUN — Preview ===\n');
        console.log(content);
        console.log('=== END PREVIEW ===');
    } else {
        fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');
        console.log(`  ✅ Written to: ${OUTPUT_FILE}`);
        console.log(`  📏 Size: ${(content.length / 1024).toFixed(1)} KB`);
    }

    console.log('');
    return content;
}

// ─────────────────────────────────────────────────────────────
// CLI
// ─────────────────────────────────────────────────────────────

if (require.main === module) {
    generate();
}

module.exports = { generate };
